service: ASGM-WFU

provider:
  name: aws
  # role: arn:aws:iam::980614374108:role/lambdaVPC
  # logs: 
  #   restApi: {role: arn:aws:iam::980614374108:role/lambdaVPC}
  runtime: nodejs10.x
  memorySize: 512
  timeout: 10
  stage: dev
  region: us-east-1
  apiGateway: {shouldStartNameWithService: true}

functions:
  api:
    handler: lambda.handler
    role: arn:aws:iam::980614374108:role/lambdaVPC
    events:
      - http:
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY
      # - http: ANY /
      # - http: ANY /{proxy+}
      # - http: ANY /about
      # - http: ANY /members
      # - http: ANY /signin
      # - http: ANY /videoupload

    